### ISSUE TITLE
Implementare i test nel codice

### ISSUE THREAD

**Issue by davideciaghi** [davideciaghi/TPA-Homework1#2]

**Comment by davideciaghi** [comment]
Buonasera @DavidLeoni,

implementando i test del device mi sono accorto che non vengono proprio eseguiti e di conseguenza non riesco a vedere se vengono superati oppure no.

Si tratta di un problema riguardante la scrittura dei test nel file `testLivella.cpp`, oppure manca qualche file necessario alla loro esecuzione?

Grazie in anticipo,

cordiali saluti.

Ciaghi Davide

**Comment by DavidLeoni** [comment]
ho appena clonato, a me funzionano. 

Forse per qualche ragione non te li aveva compilati? Prova a fare click destro su CMakeLists.txt -> Clean Reconfigure all projects.
