### ISSUE TITLE
Approvazione device

### ISSUE THREAD

**Issue by davideciaghi** [davideciaghi/TPA-Homework1#4]
Buongiorno @DavidLeoni ,

il mio device consiste nel controllo dell'inclinazione di una piastra tramite l'estensione di due pistoni.

Nonostante manchino da implementare alcune consegne dell'Homework, mi chiedevo se potesse darmi un feedback sul lavoro fino ad ora svolto.

Grazie in anticipo,

cordiali saluti.

Ciaghi Davide

**Comment by DavidLeoni** [comment]
Come tipo di device va bene

Ho guardato velocemente il codice:

- non capisco dove vorresti fare la validazione dell'input (ho guardato nel main) - al momento la vedo solo nel programma principale ma se le varie init falliscono dovrebbero tornare un NULL 
- nei commit referenzia le issue a cui si riferiscono con cancelletto, es #2
- crea un branch per ogni issue, quando è pronto lo mergi in main (o meglio ancora, un branch apposito `dev` per lo sviluppo)

**Comment by davideciaghi** [comment]
La validazione dell'input la faccio fare alla funzione `parameters_init` che domanda all'utente i parametri da inserire da terminal e controlla se sono consistenti. Una volta validati e posti in un array `arr[]` vengono assegnati alle istanze delle struct tramite le funzioni `piston_init` e `plate_init` .

Sarebbe meglio inserire i parametri delle istanze dei pistoni e della piastra, ed in seguito chiamare la funzione che mi controlla l'integrità del device? e in caso chiede di modificarli?

Grazie ancora.

Ciaghi Davide

**Comment by davideciaghi** [comment]
La validazione dell'input la faccio fare alla funzione `parameters_init` che domanda all'utente i parametri da inserire da terminal e controlla se sono consistenti. Una volta validati e posti in un array `arr[]` vengono assegnati alle istanze delle struct tramite le funzioni `piston_init` e `plate_init` .

Sarebbe meglio inserire i parametri delle istanze dei pistoni e della piastra, ed in seguito chiamare la funzione che mi controlla l'integrità del device? e in caso chiede di modificarli?

Grazie ancora.

Ciaghi Davide

@DavidLeoni

**Comment by DavidLeoni** [comment]
mischiare input di umani con validazione è sempre problematico, l'ideale sarebbe avere una funzione che dati i vari parametri fa solo la validazione, poi te la richiami da dove vuoi, init, set, etc
